name: Deploy PHP HTML Site
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.ec2-54-90-88-249.compute-1.amazonaws.com}}  # Die IP-Adresse der EC2-Instanz aus Secrets
        run: |
          # SSH Key speichern
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem
          # Git-Pull direkt auf dem Server ausführen
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@54.90.88.249 << 'EOF'
 
            cd /var/www/html
            # git fetch --all
            git reset --hard origin/main  # Setzt den Code auf die letzte GitHub-Version zurück
            git pull origin main
             #sudo chown -R www-data:www-data /var/www/html  # Besitzer setzen
            sudo chmod -R 777 /var/www/html  # Sichere Berechtigungen setzen
            # sudo systemctl restart apache2  # Apache neustarten
          EOF
          # SSH Key löschen
          rm private_key.pem
