name: Deploy PHP HTML Site
 
on:
  push:
    branches:
      - main  # Deployment wird ausgelöst, wenn auf main gepusht wird
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 Server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # PEM-Schlüssel aus GitHub Secrets
          EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2-IP aus GitHub Secrets
        run: |
          # SSH-Schlüssel speichern & Berechtigungen setzen
          echo "$SSH_KEY" | tr -d '\r' > labsuser.pem
          chmod 600 labsuser.pem

          # SSH-Verbindung testen
          ssh -i labsuser.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "echo 'SSH Connection Successful'"

          # Deployment-Prozess auf EC2 ausführen
          ssh -i labsuser.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            set -e  # Stoppt das Skript bei Fehlern
            
            # Wechsel ins Web-Verzeichnis
            sudo mkdir -p /var/www/html
            cd /var/www/html || exit 1
            
            # Prüfen, ob es ein Git-Repository ist
            if [ ! -d ".git" ]; then
              sudo git clone https://github.com/deinbenutzername/deinrepository.git .
            fi
            
            # Sicherstellen, dass keine lokalen Änderungen stören
            sudo git reset --hard
            sudo git pull origin main  # Neueste Änderungen holen
            
            # Richtige Berechtigungen setzen
            sudo chmod -R 755 /var/www/html
            
            # Apache neustarten, falls nötig
            sudo systemctl restart apache2
          EOF

          # SSH Key aus Sicherheitsgründen löschen
          rm -f labsuser.pem
